spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/sms?usessl=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never     
    
